---

- name: add apt key 
  apt_key: url=http://packages.rcrowley.org/keyring.gpg state=present

- name: add repo
  apt_repository: repo="deb http://packages.rcrowley.org {{ ansible_distribution_release }} main"

- name: install certified
  apt: pkg=certified state=present

